// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AutoRestoreSession():Promise<void>;

export function BatchDownloadFiles(arg1:string,arg2:Array<Record<string, string>>,arg3:boolean):Promise<void>;

export function BatchUploadFiles(arg1:string,arg2:Array<Record<string, string>>,arg3:boolean):Promise<void>;

export function CanAutoRestore():Promise<boolean>;

export function CheckConnection(arg1:string):Promise<models.ConnectionStatus>;

export function ClearSession():Promise<void>;

export function CloseSession(arg1:string):Promise<void>;

export function CloseTerminalSession(arg1:string):Promise<void>;

export function ConnectSSH(arg1:string):Promise<models.ConnectionResult>;

export function CreateInteractiveTerminal(arg1:string):Promise<void>;

export function CreateRemoteDirectory(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function CreateSession(arg1:string):Promise<void>;

export function DeleteConfig(arg1:string):Promise<void>;

export function DeleteRemoteDirectory(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function DeleteRemoteFile(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function DisconnectSSH(arg1:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function ExecuteCommand(arg1:string,arg2:string):Promise<string>;

export function ExecuteSSHCommand(arg1:string,arg2:string):Promise<models.CommandResult>;

export function ExecuteSudoCommand(arg1:string,arg2:string):Promise<string>;

export function GetActiveSessions():Promise<Array<models.SSHSession>>;

export function GetConfig(arg1:string):Promise<models.SSHConfig>;

export function GetConfigs():Promise<Array<models.SSHConfig>>;

export function GetRemoteFiles(arg1:string,arg2:string):Promise<models.FileListResult>;

export function GetRemoteHome(arg1:string):Promise<string>;

export function GetSessionUptime(arg1:string):Promise<string>;

export function GetTransferMode(arg1:string):Promise<string>;

export function HasConfigs():Promise<boolean>;

export function HasValidSession():Promise<boolean>;

export function IsKeySet():Promise<boolean>;

export function IsSessionActive(arg1:string):Promise<boolean>;

export function ListRemoteFiles(arg1:string,arg2:string):Promise<Array<models.FileInfo>>;

export function OpenTerminal(arg1:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestoreSession():Promise<void>;

export function SaveConfig(arg1:models.SSHConfig):Promise<void>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function SelectMultipleFiles():Promise<Array<string>>;

export function SendTerminalInput(arg1:string,arg2:string):Promise<void>;

export function SetEncryptionKey(arg1:string):Promise<void>;

export function Shutdown():Promise<void>;

export function TestSSHConnection(arg1:string):Promise<void>;

export function UploadFile(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function VerifyEncryptionKey(arg1:string):Promise<void>;

export function VerifyKeyWithSession(arg1:string):Promise<void>;
