// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchDownloadFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['BatchDownloadFiles'](arg1, arg2, arg3);
}

export function BatchUploadFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['BatchUploadFiles'](arg1, arg2, arg3);
}

export function CheckConnection(arg1) {
  return window['go']['main']['App']['CheckConnection'](arg1);
}

export function ClearSession() {
  return window['go']['main']['App']['ClearSession']();
}

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function CloseTerminalSession(arg1) {
  return window['go']['main']['App']['CloseTerminalSession'](arg1);
}

export function CreateInteractiveTerminal(arg1) {
  return window['go']['main']['App']['CreateInteractiveTerminal'](arg1);
}

export function CreateRemoteDirectory(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateRemoteDirectory'](arg1, arg2, arg3);
}

export function CreateSession(arg1) {
  return window['go']['main']['App']['CreateSession'](arg1);
}

export function DeleteConfig(arg1) {
  return window['go']['main']['App']['DeleteConfig'](arg1);
}

export function DeleteRemoteDirectory(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteRemoteDirectory'](arg1, arg2, arg3);
}

export function DeleteRemoteFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteRemoteFile'](arg1, arg2, arg3);
}

export function DownloadFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2, arg3, arg4);
}

export function ExecuteCommand(arg1, arg2) {
  return window['go']['main']['App']['ExecuteCommand'](arg1, arg2);
}

export function ExecuteSudoCommand(arg1, arg2) {
  return window['go']['main']['App']['ExecuteSudoCommand'](arg1, arg2);
}

export function GetActiveSessions() {
  return window['go']['main']['App']['GetActiveSessions']();
}

export function GetConfig(arg1) {
  return window['go']['main']['App']['GetConfig'](arg1);
}

export function GetConfigs() {
  return window['go']['main']['App']['GetConfigs']();
}

export function GetRemoteHome(arg1) {
  return window['go']['main']['App']['GetRemoteHome'](arg1);
}

export function GetSessionUptime(arg1) {
  return window['go']['main']['App']['GetSessionUptime'](arg1);
}

export function GetTransferMode(arg1) {
  return window['go']['main']['App']['GetTransferMode'](arg1);
}

export function HasConfigs() {
  return window['go']['main']['App']['HasConfigs']();
}

export function HasValidSession() {
  return window['go']['main']['App']['HasValidSession']();
}

export function IsKeySet() {
  return window['go']['main']['App']['IsKeySet']();
}

export function IsSessionActive(arg1) {
  return window['go']['main']['App']['IsSessionActive'](arg1);
}

export function ListRemoteFiles(arg1, arg2) {
  return window['go']['main']['App']['ListRemoteFiles'](arg1, arg2);
}

export function OpenTerminal(arg1) {
  return window['go']['main']['App']['OpenTerminal'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RestoreSession() {
  return window['go']['main']['App']['RestoreSession']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectMultipleFiles() {
  return window['go']['main']['App']['SelectMultipleFiles']();
}

export function SendTerminalInput(arg1, arg2) {
  return window['go']['main']['App']['SendTerminalInput'](arg1, arg2);
}

export function SetEncryptionKey(arg1) {
  return window['go']['main']['App']['SetEncryptionKey'](arg1);
}

export function Shutdown() {
  return window['go']['main']['App']['Shutdown']();
}

export function TestSSHConnection(arg1) {
  return window['go']['main']['App']['TestSSHConnection'](arg1);
}

export function UploadFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2, arg3, arg4);
}

export function VerifyEncryptionKey(arg1) {
  return window['go']['main']['App']['VerifyEncryptionKey'](arg1);
}

export function VerifyKeyWithSession(arg1) {
  return window['go']['main']['App']['VerifyKeyWithSession'](arg1);
}
